### ISSUE TITLE
Issues with movement around "top" of sphere

### ISSUE THREAD

**Issue by Speckto** [puremourning/Breakout3D#5]
If you move to the sphere top movement stops.
If you hold the key to continue movement, the view flickers.
Sometimes when you move to the top the view inverts (e.g. although the camera rotates 180 degrees)

**Comment by puremourning** [comment]
Looks like gimbal lock prevention?

**Comment by woody1287** [comment]
It's a side-effect of using the "Find Look At Rotation" calculation to point the camera at the center after applying rotation. It always forces the up-vector to be (0,1,0). A form of gimbal-lock introduced by rotating the camera around in world-co-ords rather than local co-ords. If you can come up with the math to perform the rotation/movement in local co-ords then this would go away (and the camera would freely pivot past the top and bottom because those concepts don't exist in the local co-ords).
